<?php
return array(
	'application_env' => 'production',
	'editor' => 'ckeditor',
	'list_limit' => '20',
	'helpurl' => 'http://www.hubzero.org',
	'debug' => '0',
	'debug_lang' => '0',
	'feed_limit' => '10',
	'feed_email' => 'author',
	'secret' => 'CDQpt56kK6',
	'gzip' => '0',
	'error_reporting' => 'default',
	'api_server' => '1',
	'xmlrpc_server' => '',
	'log_path' => '/var/www/hsscommons/app/logs',
	'tmp_path' => '/var/www/hsscommons/app/tmp',
	'live_site' => '',
	'force_ssl' => '2',
	'offset' => 'America/Vancouver',
	'sitename' => 'hsscommons',
	'robots' => '',
	'captcha' => 'image',
	'access' => '1',
	'profile' => '0',
	'log_post_data' => '0',
);